package com.yaokongqi.remote.model

data class KeyboardKey(
    val label: String,
    val vk: Int,
    val mods: Int = 0,
    val weight: Float = 1f,
)

object FullKeyboardLayout {
    val rows: List<List<KeyboardKey>> = listOf(
        listOf(
            KeyboardKey("Esc", 0x1B),
            KeyboardKey("F1", 0x70),
            KeyboardKey("F2", 0x71),
            KeyboardKey("F3", 0x72),
            KeyboardKey("F4", 0x73),
            KeyboardKey("F5", 0x74),
            KeyboardKey("F6", 0x75),
            KeyboardKey("F7", 0x76),
            KeyboardKey("F8", 0x77),
            KeyboardKey("F9", 0x78),
            KeyboardKey("F10", 0x79),
            KeyboardKey("F11", 0x7A),
            KeyboardKey("F12", 0x7B),
        ),
        listOf(
            KeyboardKey("`", 0xC0),
            KeyboardKey("1", 0x31),
            KeyboardKey("2", 0x32),
            KeyboardKey("3", 0x33),
            KeyboardKey("4", 0x34),
            KeyboardKey("5", 0x35),
            KeyboardKey("6", 0x36),
            KeyboardKey("7", 0x37),
            KeyboardKey("8", 0x38),
            KeyboardKey("9", 0x39),
            KeyboardKey("0", 0x30),
            KeyboardKey("-", 0xBD),
            KeyboardKey("=", 0xBB),
            KeyboardKey("删除", 0x08, weight = 1.5f),
        ),
        listOf(
            KeyboardKey("Tab", 0x09, weight = 1.3f),
            KeyboardKey("Q", 0x51),
            KeyboardKey("W", 0x57),
            KeyboardKey("E", 0x45),
            KeyboardKey("R", 0x52),
            KeyboardKey("T", 0x54),
            KeyboardKey("Y", 0x59),
            KeyboardKey("U", 0x55),
            KeyboardKey("I", 0x49),
            KeyboardKey("O", 0x4F),
            KeyboardKey("P", 0x50),
            KeyboardKey("[", 0xDB),
            KeyboardKey("]", 0xDD),
            KeyboardKey("\\", 0xDC),
        ),
        listOf(
            KeyboardKey("Caps", 0x14, weight = 1.5f),
            KeyboardKey("A", 0x41),
            KeyboardKey("S", 0x53),
            KeyboardKey("D", 0x44),
            KeyboardKey("F", 0x46),
            KeyboardKey("G", 0x47),
            KeyboardKey("H", 0x48),
            KeyboardKey("J", 0x4A),
            KeyboardKey("K", 0x4B),
            KeyboardKey("L", 0x4C),
            KeyboardKey(";", 0xBA),
            KeyboardKey("'", 0xDE),
            KeyboardKey("Enter", 0x0D, weight = 1.5f),
        ),
        listOf(
            KeyboardKey("Shift", 0x10, weight = 1.8f),
            KeyboardKey("Z", 0x5A),
            KeyboardKey("X", 0x58),
            KeyboardKey("C", 0x43),
            KeyboardKey("V", 0x56),
            KeyboardKey("B", 0x42),
            KeyboardKey("N", 0x4E),
            KeyboardKey("M", 0x4D),
            KeyboardKey(",", 0xBC),
            KeyboardKey(".", 0xBE),
            KeyboardKey("/", 0xBF),
            KeyboardKey("Shift", 0x10, weight = 1.8f),
        ),
        listOf(
            KeyboardKey("Ctrl", 0x11, weight = 1.2f),
            KeyboardKey("Win", 0x5B, weight = 1.2f),
            KeyboardKey("Alt", 0x12, weight = 1.2f),
            KeyboardKey("空格", 0x20, weight = 4f),
            KeyboardKey("Alt", 0x12, weight = 1.2f),
            KeyboardKey("←", 0x25),
            KeyboardKey("↓", 0x28),
            KeyboardKey("↑", 0x26),
            KeyboardKey("→", 0x27),
        ),
    )
}
